FROM jinxprotocol-base

COPY ./testing/snapshotting/snapshot.sh /jinxprotocol/snapshot.sh

RUN go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@v1.4.0

ENTRYPOINT ["/jinxprotocol/snapshot.sh"]
