// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: jinxprotocol/clob/block_rate_limit_config.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Defines the block rate limits for CLOB specific operations.
type BlockRateLimitConfiguration struct {
	// How many short term order attempts (successful and failed) are allowed for
	// an account per N blocks. Note that the rate limits are applied
	// in an AND fashion such that an order placement must pass all rate limit
	// configurations.
	//
	// Specifying 0 values disables this rate limit.
	MaxShortTermOrdersPerNBlocks []MaxPerNBlocksRateLimit `protobuf:"bytes,1,rep,name=max_short_term_orders_per_n_blocks,json=maxShortTermOrdersPerNBlocks,proto3" json:"max_short_term_orders_per_n_blocks"`
	// How many stateful order attempts (successful and failed) are allowed for
	// an account per N blocks. Note that the rate limits are applied
	// in an AND fashion such that an order placement must pass all rate limit
	// configurations.
	//
	// Specifying 0 values disables this rate limit.
	MaxStatefulOrdersPerNBlocks []MaxPerNBlocksRateLimit `protobuf:"bytes,2,rep,name=max_stateful_orders_per_n_blocks,json=maxStatefulOrdersPerNBlocks,proto3" json:"max_stateful_orders_per_n_blocks"`
	// How many short term order cancellation attempts (successful and failed) are
	// allowed for an account per N blocks. Note that the rate limits are
	// applied in an AND fashion such that an order cancellation must pass all
	// rate limit configurations.
	//
	// Specifying 0 values disables this rate limit.
	MaxShortTermOrderCancellationsPerNBlocks []MaxPerNBlocksRateLimit `protobuf:"bytes,3,rep,name=max_short_term_order_cancellations_per_n_blocks,json=maxShortTermOrderCancellationsPerNBlocks,proto3" json:"max_short_term_order_cancellations_per_n_blocks"`
}

func (m *BlockRateLimitConfiguration) Reset()         { *m = BlockRateLimitConfiguration{} }
func (m *BlockRateLimitConfiguration) String() string { return proto.CompactTextString(m) }
func (*BlockRateLimitConfiguration) ProtoMessage()    {}
func (*BlockRateLimitConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1e838f538e65263, []int{0}
}
func (m *BlockRateLimitConfiguration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockRateLimitConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockRateLimitConfiguration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockRateLimitConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRateLimitConfiguration.Merge(m, src)
}
func (m *BlockRateLimitConfiguration) XXX_Size() int {
	return m.Size()
}
func (m *BlockRateLimitConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRateLimitConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRateLimitConfiguration proto.InternalMessageInfo

func (m *BlockRateLimitConfiguration) GetMaxShortTermOrdersPerNBlocks() []MaxPerNBlocksRateLimit {
	if m != nil {
		return m.MaxShortTermOrdersPerNBlocks
	}
	return nil
}

func (m *BlockRateLimitConfiguration) GetMaxStatefulOrdersPerNBlocks() []MaxPerNBlocksRateLimit {
	if m != nil {
		return m.MaxStatefulOrdersPerNBlocks
	}
	return nil
}

func (m *BlockRateLimitConfiguration) GetMaxShortTermOrderCancellationsPerNBlocks() []MaxPerNBlocksRateLimit {
	if m != nil {
		return m.MaxShortTermOrderCancellationsPerNBlocks
	}
	return nil
}

// Defines a rate limit over a specific number of blocks.
type MaxPerNBlocksRateLimit struct {
	// How many blocks the rate limit is over.
	// Specifying 0 is invalid.
	NumBlocks uint32 `protobuf:"varint,1,opt,name=num_blocks,json=numBlocks,proto3" json:"num_blocks,omitempty"`
	// What the limit is for `num_blocks`.
	// Specifying 0 is invalid.
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *MaxPerNBlocksRateLimit) Reset()         { *m = MaxPerNBlocksRateLimit{} }
func (m *MaxPerNBlocksRateLimit) String() string { return proto.CompactTextString(m) }
func (*MaxPerNBlocksRateLimit) ProtoMessage()    {}
func (*MaxPerNBlocksRateLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1e838f538e65263, []int{1}
}
func (m *MaxPerNBlocksRateLimit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MaxPerNBlocksRateLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MaxPerNBlocksRateLimit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MaxPerNBlocksRateLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxPerNBlocksRateLimit.Merge(m, src)
}
func (m *MaxPerNBlocksRateLimit) XXX_Size() int {
	return m.Size()
}
func (m *MaxPerNBlocksRateLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxPerNBlocksRateLimit.DiscardUnknown(m)
}

var xxx_messageInfo_MaxPerNBlocksRateLimit proto.InternalMessageInfo

func (m *MaxPerNBlocksRateLimit) GetNumBlocks() uint32 {
	if m != nil {
		return m.NumBlocks
	}
	return 0
}

func (m *MaxPerNBlocksRateLimit) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockRateLimitConfiguration)(nil), "jinxprotocol.clob.BlockRateLimitConfiguration")
	proto.RegisterType((*MaxPerNBlocksRateLimit)(nil), "jinxprotocol.clob.MaxPerNBlocksRateLimit")
}

func init() {
	proto.RegisterFile("jinxprotocol/clob/block_rate_limit_config.proto", fileDescriptor_c1e838f538e65263)
}

var fileDescriptor_c1e838f538e65263 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x40, 0x5b, 0x50, 0x13, 0xd7, 0x78, 0xb0, 0x21, 0x86, 0x88, 0x56, 0xc2, 0x09, 0x0f, 0xb6,
	0x89, 0x1a, 0x3f, 0x00, 0xae, 0xa2, 0x04, 0x3d, 0x79, 0xd9, 0x6c, 0xd7, 0xa5, 0xac, 0xee, 0xee,
	0x90, 0xed, 0x96, 0x94, 0xbf, 0x30, 0xfe, 0x83, 0xff, 0xc2, 0x91, 0xa3, 0x27, 0x63, 0xe0, 0x47,
	0x4c, 0x17, 0x02, 0x28, 0x9c, 0xb8, 0xb5, 0xd3, 0x99, 0xf7, 0x66, 0xa6, 0x83, 0xc2, 0x57, 0xae,
	0xb2, 0xbe, 0x06, 0x03, 0x14, 0x44, 0x48, 0x05, 0x44, 0x61, 0x24, 0x80, 0xbe, 0x61, 0x4d, 0x0c,
	0xc3, 0x82, 0x4b, 0x6e, 0x30, 0x05, 0xd5, 0xe5, 0x71, 0x60, 0xb3, 0xbc, 0xa3, 0xd5, 0x82, 0x20,
	0x2f, 0x38, 0x29, 0xc5, 0x10, 0x83, 0x0d, 0x85, 0xf9, 0xd3, 0x2c, 0xb1, 0xf6, 0x59, 0x44, 0x95,
	0x46, 0x8e, 0xea, 0x10, 0xc3, 0xee, 0x72, 0x50, 0xd3, 0x72, 0x52, 0x4d, 0x0c, 0x07, 0xe5, 0x0d,
	0x51, 0x4d, 0x92, 0x0c, 0x27, 0x3d, 0xd0, 0x06, 0x1b, 0xa6, 0x25, 0x06, 0xfd, 0xc2, 0x74, 0x82,
	0xfb, 0x4c, 0x63, 0x85, 0x6d, 0x17, 0x49, 0xd9, 0xad, 0x16, 0xeb, 0x07, 0x57, 0x17, 0xc1, 0x9a,
	0x35, 0x68, 0x91, 0xac, 0xcd, 0xf4, 0xbd, 0x55, 0x24, 0x0b, 0x47, 0x63, 0x67, 0xf4, 0x7d, 0xee,
	0x74, 0x4e, 0x25, 0xc9, 0x1e, 0x73, 0xf2, 0x13, 0xd3, 0xf2, 0xc1, 0x72, 0x97, 0xc9, 0xde, 0x00,
	0x55, 0xad, 0xda, 0x10, 0xc3, 0xba, 0xa9, 0xd8, 0x28, 0x2e, 0x6c, 0x27, 0xae, 0xe4, 0xe2, 0x39,
	0x77, 0xcd, 0xfb, 0xe1, 0xa2, 0x70, 0xd3, 0xcc, 0x98, 0x12, 0x45, 0x99, 0x10, 0x76, 0x31, 0xff,
	0xfa, 0x28, 0x6e, 0xd7, 0x47, 0x7d, 0x6d, 0x01, 0xcd, 0x55, 0xc7, 0xb2, 0xb0, 0xd6, 0x42, 0xc7,
	0x9b, 0x49, 0xde, 0x19, 0x42, 0x2a, 0x95, 0xcb, 0x3f, 0xe1, 0xd6, 0x0f, 0x3b, 0xfb, 0x2a, 0x95,
	0xf3, 0x69, 0x4a, 0x68, 0xd7, 0xde, 0x47, 0xb9, 0x60, 0xbf, 0xcc, 0x5e, 0x1a, 0xed, 0xd1, 0xc4,
	0x77, 0xc7, 0x13, 0xdf, 0xfd, 0x99, 0xf8, 0xee, 0xfb, 0xd4, 0x77, 0xc6, 0x53, 0xdf, 0xf9, 0x9a,
	0xfa, 0xce, 0xf3, 0x6d, 0xcc, 0x4d, 0x2f, 0x8d, 0x02, 0x0a, 0xf2, 0xef, 0xd5, 0x0d, 0x6e, 0x2e,
	0x69, 0x8f, 0x70, 0x15, 0x2e, 0x22, 0xd9, 0xec, 0x12, 0xcd, 0xb0, 0xcf, 0x92, 0x68, 0xcf, 0x86,
	0xaf, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x87, 0xca, 0x47, 0x4e, 0xab, 0x02, 0x00, 0x00,
}

func (m *BlockRateLimitConfiguration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockRateLimitConfiguration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockRateLimitConfiguration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MaxShortTermOrderCancellationsPerNBlocks) > 0 {
		for iNdEx := len(m.MaxShortTermOrderCancellationsPerNBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxShortTermOrderCancellationsPerNBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBlockRateLimitConfig(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.MaxStatefulOrdersPerNBlocks) > 0 {
		for iNdEx := len(m.MaxStatefulOrdersPerNBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxStatefulOrdersPerNBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBlockRateLimitConfig(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.MaxShortTermOrdersPerNBlocks) > 0 {
		for iNdEx := len(m.MaxShortTermOrdersPerNBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxShortTermOrdersPerNBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBlockRateLimitConfig(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MaxPerNBlocksRateLimit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MaxPerNBlocksRateLimit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MaxPerNBlocksRateLimit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Limit != 0 {
		i = encodeVarintBlockRateLimitConfig(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x10
	}
	if m.NumBlocks != 0 {
		i = encodeVarintBlockRateLimitConfig(dAtA, i, uint64(m.NumBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBlockRateLimitConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovBlockRateLimitConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BlockRateLimitConfiguration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MaxShortTermOrdersPerNBlocks) > 0 {
		for _, e := range m.MaxShortTermOrdersPerNBlocks {
			l = e.Size()
			n += 1 + l + sovBlockRateLimitConfig(uint64(l))
		}
	}
	if len(m.MaxStatefulOrdersPerNBlocks) > 0 {
		for _, e := range m.MaxStatefulOrdersPerNBlocks {
			l = e.Size()
			n += 1 + l + sovBlockRateLimitConfig(uint64(l))
		}
	}
	if len(m.MaxShortTermOrderCancellationsPerNBlocks) > 0 {
		for _, e := range m.MaxShortTermOrderCancellationsPerNBlocks {
			l = e.Size()
			n += 1 + l + sovBlockRateLimitConfig(uint64(l))
		}
	}
	return n
}

func (m *MaxPerNBlocksRateLimit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumBlocks != 0 {
		n += 1 + sovBlockRateLimitConfig(uint64(m.NumBlocks))
	}
	if m.Limit != 0 {
		n += 1 + sovBlockRateLimitConfig(uint64(m.Limit))
	}
	return n
}

func sovBlockRateLimitConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBlockRateLimitConfig(x uint64) (n int) {
	return sovBlockRateLimitConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BlockRateLimitConfiguration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlockRateLimitConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockRateLimitConfiguration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockRateLimitConfiguration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxShortTermOrdersPerNBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRateLimitConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBlockRateLimitConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRateLimitConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxShortTermOrdersPerNBlocks = append(m.MaxShortTermOrdersPerNBlocks, MaxPerNBlocksRateLimit{})
			if err := m.MaxShortTermOrdersPerNBlocks[len(m.MaxShortTermOrdersPerNBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxStatefulOrdersPerNBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRateLimitConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBlockRateLimitConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRateLimitConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxStatefulOrdersPerNBlocks = append(m.MaxStatefulOrdersPerNBlocks, MaxPerNBlocksRateLimit{})
			if err := m.MaxStatefulOrdersPerNBlocks[len(m.MaxStatefulOrdersPerNBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxShortTermOrderCancellationsPerNBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRateLimitConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBlockRateLimitConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBlockRateLimitConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxShortTermOrderCancellationsPerNBlocks = append(m.MaxShortTermOrderCancellationsPerNBlocks, MaxPerNBlocksRateLimit{})
			if err := m.MaxShortTermOrderCancellationsPerNBlocks[len(m.MaxShortTermOrderCancellationsPerNBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBlockRateLimitConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBlockRateLimitConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MaxPerNBlocksRateLimit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlockRateLimitConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MaxPerNBlocksRateLimit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MaxPerNBlocksRateLimit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumBlocks", wireType)
			}
			m.NumBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRateLimitConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumBlocks |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockRateLimitConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBlockRateLimitConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBlockRateLimitConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBlockRateLimitConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBlockRateLimitConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlockRateLimitConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlockRateLimitConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBlockRateLimitConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBlockRateLimitConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBlockRateLimitConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBlockRateLimitConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBlockRateLimitConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBlockRateLimitConfig = fmt.Errorf("proto: unexpected end of group")
)
